### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by renehsz** [vassvik/odin-stb#2]
This library is awesome, however it is impossible to use for non-personal projects because you haven't added a license.

It would be great if you license this under some open source license... If not, you can create your own license...

However currently nobody knows whether it is legal to use this library or not. Therefore please add some kind of license!

**Comment by vassvik** [comment]
Hey. Thanks for letting my know. I'm way too sloppy adding licenses to new repos. I'll do the same thing for my other repos as well, also making sure to respect the licenses for the projects I'm bindings to.
