### ISSUE TITLE
Makefile doesn't seem to work

### ISSUE THREAD

**Issue by MagpieMcGraw** [vassvik/odin-stb#4]
So I downloaded this and followed the instructions, but the makefile failed to create the static libraries. Here's how it looked after I typed 'make'.
![screenshot at 2018-02-26 14-22-51](https://user-images.githubusercontent.com/17641521/36670434-0286cd08-1b01-11e8-82e5-a2bf29d61d2c.png)

I actually managed to get a static library for stb_image, by editing the makefile to use the following path: /lib/stb_image.a. I suppose that might work for the rest of the files too, but I only tried it on stb_image. I copied the created static lib to the folder of my program, along wtih stb_image.odin, imported stb_image.odin and successfully used the 'load' function. To summarize: the bindings seem to work, but the makefile doesn't work as-is to generate the static libraries.

**Comment by vassvik** [comment]
Hmm, I think the issue is that the repo doesn't contain the `lib` folder as is, so you need to create it first. I should perhaps add that to the makefile...

**Comment by MagpieMcGraw** [comment]
Just now I made a lib folder and that totally worked! I had tried making a lib folder before, but I think I did it in the src directory, which didn't work.
