### ISSUE TITLE
init_context should take a pointer to a node as an argument?

### ISSUE THREAD

**Issue by MagpieMcGraw** [vassvik/odin-stb#5]
I'm pretty sure you have a typo. The stbrp_init_target function takes a pointer to a node. Yours just takes a node. I modified your file because it wouldn't work otherwise.
![screenshot at 2018-02-28 18-55-52](https://user-images.githubusercontent.com/17641521/36800927-5ba5cc90-1cb9-11e8-8076-8101c309d784.png)

**Comment by vassvik** [comment]
Ah, you are right. Such is the problem of creating bindings manually - typos slip in. It's not even a complete binding, since I haven't really used it for much yet, but I might in the near future.
